name: PHP tests

on: [push, pull_request]

jobs:
  php-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["7.3", "7.4", "8.0", "8.1"]
        laravel: ["^6.20.44", "^7.30.6", "^8.83", "^9.0"]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
          - laravel: "^6.20.44"
            testbench: "^4.18"
          - laravel: "^7.30.6"
            testbench: "^5.18"
          - laravel: "^8.83"
            testbench: "^6.23"
          - laravel: "^9.0"
            testbench: "^7.0"

    name: PHP ${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, intl
        ini-values: post_max_size=256M, short_open_tag=On
        coverage: xdebug        
        tools: phpunit

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
        composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction
      
    - name: Execute PHPUnit tests
      run: vendor/bin/phpunit --configuration phpunit.xml --coverage-text


